name: absen_simple
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  dotted_border: ^2.1.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.2
  lottie: ^3.2.0
  google_mlkit_face_detection: ^0.12.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
